### PR TITLE
Add flag to disable exclusion of changes on master

### PR DESCRIPTION
**Pull request by setpill**
Followup on #347

### CODE REVIEW

**Comment by quasilyte** [comment]
Looks good to me.
@YuriyNasretdinov, what do you think?

**Comment by YuriyNasretdinov** [comment]
I expected that -git-ignore-master flag would ignore changes from master, not ignore "ignoring changes from master". I would rename the flag to `-git-exclude-origin-master-changes` and set it to true by default. Yes, it is a long flag name but at least it's not misleading.

Otherwise the implementation is probably ok but of course we probably want to have some tests for this if we are ever going to change this logic.

**Comment by setpill** [comment]
Yes I struggled a bit with the naming. Will rethink.

**Comment by setpill** [comment]
Flag renamed to `-git-disable-compensate-master`. Hopefully that, combined with the help text, is clear in meaning.

**Comment by quasilyte** [comment]
Thank you for the contribution!

**Comment by YuriyNasretdinov** [comment]
We would probably also want to document the `-git-*` flags better as well actually :).

**Comment by YuriyNasretdinov** [comment]
But that is a separate issue from this PR.

**Comment by YuriyNasretdinov** [comment]
Created https://github.com/VKCOM/noverify/issues/349 to track that

**Pull request merged**
