### PR TITLE
Add reports for non-literal key duplicates in dupArrayKeys

### PR DESCRIPTION
**Pull request by hazzus**
Solving #325. Now separately looks at duplicates in `scalar.Dnumber`, `expr.ConstFetch`, `expr.ClassConstFetch`. Moreover, it adds to dupArrayKeys the check for any other `node.Node` satisfying `sideEffectFree` condition.
This PR also improves Lnumber duplicates check, considering they may be written in different formats. 
Example code:
```php
$example5 = [
  17 => 1,
  0x11 => 3, // duplicate key 17
  0b10001 => 2, // duplicate key 17
];
```
The only help needed: Does it make sense to use a `printer` in default (`sideEffectFree()`) case? I just didn't come up with any other idea (besides using a case switch for everything).

PS: This PR is a test task for the internship in VK in the backend-infrastructure team.

### CODE REVIEW

**Comment by quasilyte** [comment]
Hello, Pavel!

Thank you for your participation. :)

Here is the agenda:
* June 20: first review round. Here you'll get the code review.
* June 21: your opportunity to make the final changes and address the code review.
* June 22: on this date, most PRs will be evaluated.

You're encouraged to make improvements in your own fork (potentially private) and
send the updates to this PR somewhere closer to the 20th of June (if there are any).

**Comment by quasilyte** [comment]
> The only help needed: Does it make sense to use a printer in default (sideEffectFree()) case? I just didn't come up with any other idea (besides using a case switch for everything).

See the previous message. Please send me a mail with all your questions somewhere around the 15th of June and I'll answer them unless they're asking for a concrete code. :)

I could answer here, but we don't want to make it too easy for other applicants. :wink:

**Comment by hazzus** [comment]
**Update**:
In last few commits I moved the implementation to NodeSet. It was considered as the solution in issue. Code is simpler, solution is more abstract, it avoids some overhead on checks.
However, this reverts checks of different formats for integers and casted doubles. As it was mentioned, this is a rare case.
I'm still not sure about `ValidArrayKey` check, it may be more completed in the future.

**Comment by hazzus** [comment]
**Update**:
1. Moves tests from regression to basic
2. Removes redundant quotes in the check message
3. Extends `ValidArrayKey` check: now checks types of some nodes (oriented on `exprType` function). New version of validation doesn't check precision of typeMap, however, it checks that **all** possible types **must be** an arrays or objects in order not to create a false-positive output (so if `mixed`, `unknown_from_list` occurs, it satisfies them as valid keys)

**Comment by quasilyte** [comment]
Thank you for your participation!
Unfortunately, we had to choose only one intern at this time.
HRs should have been contacted you by this point.

**Pull request closed without merging**
