### PR TITLE
Solving issue #324 and #325

### PR DESCRIPTION
**Pull request by FadeevSergey**
#325
Added diagnostics duplication of non-literal keys added. Now the following keys are checked:
```
scalar.Dnumber,
node.SimpleVar,
expr.ConstFetch,
binary.Concat,
expr.ClassConstFetch,
expr.PropertyFetch,
expr.ArrayDimFetch,
expr.StaticPropertyFetch,
expr.Ternary,
expr.FunctionCall,
expr.MethodCall,
expr.StaticCall,
expr.InstanceOf 
```
and everyone `node.Node` that satisfying `sideEffectFree`.

Improved node.Lnumber checking. Now the same numbers in different number systems are considered the same. For example: 
```
$array = [
    1234 => 7,
    02322 => 8,  // 02322 = 1234 duplicate
    0x4D2 => 9,  // 0x4D2 = 1234 duplicate
    0b10011010010 => 10,// 0b10011010010 = 1234 duplicate
    1_234 => 11, // 1_234 = 1234 duplicate
];
```
Added new type of warnings - `illegalArrayKeys`. Example: 
```
class A{}

$arr = [
    new A() => 1,  // Illegal array key new A(), 
    [1, 2, 3] => 2,// Illegal array key [1, 2, 3]
    function () {} => 3, // Illegal array key function () {}
];
```

#324 
Added analysis of the following class-scoped:
`stmt.PropertyList:`
> `expr.ClassConstFetch`
> `expr.Array`
> `expr.Ternary`
> `expr.ConstFetch`

`stmt.ClassConstList:`
> `expr.ClassConstFetch`
> `expr.Array`
> `expr.Ternary`
> `expr.ConstFetch`

Example: 

```
class T
{
    const C = 1;

    const C1 = self::UNDEFCONST;              // undefined class constant
    const C2 = self::C ? "var" : "var";       // then/else operands are identical

    public $var1 = self::UNDEFCONST;          // undefined class constant
    public $var2 = self::C ? "var1" : "var1"; // then/else operands are identical

    public $publicArray = [
        'key1' => 'somethingInPublic',
        'key2' => 'other_thingInPublic',
        'key1' => 'third_thingInPublic', // duplicate key 'key1'
    ];

    const constArray = [
        'key1' => 'somethingInConst',
        'key2' => 'other_thingInConst',
        'key1' => 'third_thingInConst', // duplicate key 'key1'
    ];

    public static $staticArray = [
        'key1' => 'somethingInStatic',
        'key2' => 'other_thingInStatic',
        'key1' => 'third_thingInStatic', // duplicate key 'key1'
    ];

    public $mixArrayKeys = [
        1 => 1,
	2,
	3,
    ];
}
```

### Behavior before
No warnings.

### Actual behavior
```
const C1 = self::UNDEFCONST; - undefined class constant
const C2 = self::C ? "var" : "var"; - then/else operands are identical

public $var1 = self::UNDEFCONST; - undefined class constant
public $var2 = self::C ? "var1" : "var1"; - then/else operands are identical

'key1' => 'third_thingInPublic', - duplicate key 'key1'
'key1' => 'third_thingInConst', - duplicate key 'key1'
'key1' => 'third_thingInStatic', - duplicate key 'key1'

    public $mixArrayKeys = [
        1 => 1,
	2,
	3,
    ]; - Mixing implicit and explicit array keys
```

Thank you for the attention :)

### CODE REVIEW

**Comment by quasilyte** [comment]
Hello.

It's good to see that you've solved several problems, but there are some issues with doing that in one pull request.

* It's harder to review this way. More code => need more tests => a lot of things to check out.
* It's impossible to revert logically separate changes without doing the manual work if several fixes are intermixed.
* If it's a part of the internship challenge it would be a little unfair if the one who sends more code would win. You're very welcome to send a separate PR and participate in its development outside of the internship challenge. It won't affect your passing score, but you'll definitely get something that you can add to your resume. Oh, and a lot of respect of course. :sweat_smile: 

So, I suggest having another PR that concentrates on #325.
What do you think?

**Comment by quasilyte** [comment]
Here is some general info regarding the process.

--

Here is the agenda:
* After June 15: I'll answer some implementation-related questions if you send them to `quasilyte@gmail.com`, but without big spoilers! :)
* June 20: first review round. Here you'll get the code review.
* June 21: your opportunity to make the final changes and address the code review.
* June 22: on this date, most PRs will be evaluated.

You're encouraged to make improvements in your own fork (potentially private) and
send the updates to this PR somewhere closer to the 20th of June (if there are any).

**Comment by FadeevSergey** [comment]
> So, I suggest having another PR that concentrates on #325.
> What do you think?

Of course I can do it. 

I have one question about the tests.
About 700 of the 900 lines that I added are tests. Nothing that they take up so much space? I do not think that a large number of tests will interfere.

**Comment by quasilyte** [comment]
> About 700 of the 900 lines that I added are tests. Nothing that they take up so much space? I do not think that a large number of tests will interfere.

It really depends on the quality of the tests.
Hint: some test lines may not improve the test coverage.

I could give a more specific answer, but I need to avoid giving a lot of hints at this stage. :wink:

**Comment by quasilyte** [comment]
Don't forget to send a PR that will be used for the internship challenge.
It should by the 20th of June.

**Comment by FadeevSergey** [comment]
Thank you for reminding)
I plan to send PR closer to June 20 as you recommended.

**Pull request closed without merging**
