### PR TITLE
inherit base method param types

### PR DESCRIPTION
**Pull request by quasilyte**
If no other type info about params is available,
walk base types to find matching method and see whether
it has proper types info for that parameter.

Do this only for interfaces.

This makes it possible to resolve both input and output
types of methods that implement some interface. In turn,
this makes "undefined method" go away if method had no
PHPDoc that specified the parameter type that was used.

Phpstorm and phpdoc utility do more or less the same thing.

Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

### CODE REVIEW

**Comment by quasilyte** [comment]
@YuriyNasretdinov, maybe there are better ways?

**Comment by YuriyNasretdinov** [comment]
The only real thing that bothers me is why is there a limit on params count :). It should be encoded as an argument and you just need to add something like wrap3 and unwrap3 functions

**Comment by quasilyte** [comment]
Like using `<string>` of 1 character and check it's value? I though of adding `<uint8>` field later, but maybe storing it as a string is not a big deal.

**Comment by YuriyNasretdinov** [comment]
You don't have to use string. You can use the code that formats length and
store it as an integer (shouldn't use binary encoding though)

**Comment by quasilyte** [comment]
OK, I'll take a look.

**Comment by quasilyte** [comment]
I'll try to reproduce it.

**Comment by quasilyte** [comment]
We can get a pipe if we print wrapped type. It'll look like this:
```
	|0800FooClass0900barMethod
(First char is tab)
```
If we split type that are in this encoded representation, that will be a problem I guess.

**Comment by YuriyNasretdinov** [comment]
I encountered some places where it is presumed that "|" is a separator between type names, although I am not sure where exactly it caused any problems. The only thing I remember is that it did mess things up :)

**Comment by quasilyte** [comment]
Should be safe now. I'm using hex-encoding for `<uint8>`, so it consumes 2 bytes, but will never look like `|`. Tests also cover this particular peculiarity from now on.

**Pull request merged**
